package com.maintenance_match.notification.service;

import com.maintenance_match.notification.dto.NotificationRequest;
import com.maintenance_match.notification.model.Notification;
import com.maintenance_match.notification.repository.NotificationRepository;
import com.maintenance_match.notification.service.impl.NotificationServiceImpl;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

@ExtendWith(MockitoExtension.class)
public class NotificationServiceImplTest {

    @Mock
    private NotificationRepository notificationRepository;

    @InjectMocks
    private NotificationServiceImpl notificationService;

    @Test
    void sendNotification_shouldBuildAndSaveNotificationEntity() {
        // Given
        NotificationRequest request = NotificationRequest.builder()
                .userId(UUID.randomUUID())
                .message("Your job has been completed.")
                .build();

        // When
//        notificationService.sendNotification(request);

        // Then
        ArgumentCaptor<Notification> notificationCaptor = ArgumentCaptor.forClass(Notification.class);
        verify(notificationRepository, times(1)).save(notificationCaptor.capture());

        // Assert the properties of the captured object
        Notification savedNotification = notificationCaptor.getValue();
        assertThat(savedNotification).isNotNull();
        assertThat(savedNotification.getRecipientId()).isEqualTo(request.getUserId());
        assertThat(savedNotification.getMessage()).isEqualTo("Your job has been completed.");
        assertThat(savedNotification.isRead()).isFalse(); // Should default to unread
        assertThat(savedNotification.getId()).isNull(); // The ID is generated by the database, so it's null before saving
    }
}
